Update userguide
CS2103-AY1819S2-W10-1/main pull request #4
Opened 2019-02-17 12:58 UTC by epicfailname

Left to do:
- Update Command Summary
- Add in examples for command format
- Update FAQ

2019-02-17 14:44 UTC, rlrh requested changes
Perhaps we can use our marketing copy here, something like:
README helps you discover, curate and read more content you care about in less time. It is a combined bookmark manager and feed reader with features like offline capability, distraction-free reading view, powerful organization options and more. It is designed for heavy content consumers with irregular internet access, whether because of having to fly often or internet access being too expensive. It is optimized for...

2019-02-18 03:40 UTC, thomastanck requested changes
LGTM, but we could add @rlrh's UI mockup to this PR before merging

2019-02-18 12:28 UTC, epicfailname commented
> Perhaps we can use our marketing copy here, something like:
> README helps you discover, curate and read more content you care about in less time. It is a combined bookmark manager and feed reader with features like offline capability, distraction-free reading view, powerful organization options and more. It is designed for heavy content consumers with irregular internet access, whether because of having to fly often or internet access being too expensive. It is optimized for...

2019-02-18 13:46 UTC, rlrh approved these changes

2019-02-18 15:28 UTC, thomastanck approved these changes

2019-02-18 15:37 UTC, merged