Update config.json
CS2103-AY1819S2-W10-1/main pull request #94
Opened 2019-03-20 03:30 UTC by thomastanck

2019-03-20 04:40 UTC, qjqqyy requested changes

2019-03-20 04:40 UTC, qjqqyy commented on _reposense/config.json
> +      "displayName": ".........",
typo?

2019-03-22 03:00 UTC, thomastanck commented on _reposense/config.json
> +      "displayName": ".........",
Fixed

2019-03-24 18:15 UTC, qjqqyy approved these changes

2019-03-24 18:16 UTC, merged